IF (${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
    set(PLATFORM_BSD "1")
ENDIF (${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")

IF (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(PLATFORM_LINUX "1")
ENDIF (${CMAKE_SYSTEM_NAME} MATCHES "Linux")

IF (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(PLATFORM_MACOSX "1")
ENDIF (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")